### ISSUE TITLE
http error 404 not found

### ISSUE THREAD

**Issue by 0ec3** [wibisono/curious-trends#2]
kenapa pas server udah berjalan trus saya jalanin localhost:9000/#/trends/[hashtags/apa], malah error ??
![wibisono](https://user-images.githubusercontent.com/25809154/41046899-7f7fdb4c-69d5-11e8-9042-6f76f15cd462.png)

**Comment by wibisono** [comment]
README udah saya update, sorry kurang lengkap infonya :)

    sbt compileStatics

Abis itu baru:

    sbt run
